config/routes.rb
Exo::Engine.routes.draw do
  if ['development', 'test'].include?(Rails.env)
    _site_grid_fs_path = '/grid_fs/exo/:site_slug_id/'
    get "#{_site_grid_fs_path}/resources/:resource_slug_id/:item_slug_id/:field_slug_id/*file_name", to: 'gridfs#item_asset'
    get "#{_site_grid_fs_path}/:id/*file_name", to: 'gridfs#asset'
  end

  root 'pages#serve_page', route_path: '/'

  # get '/admin', to: 'admin/site#show', as: 'contributor_root'
  # 
  # get '/admin', to: 'admin/site#show', as: 'admin_contributor_root'
    
  put '/admin/pages/blocks', to: 'admin/ckeditor_blocks#update'

  devise_for(
    :contributors,
    class_name: "Exo::Contributor", module: :devise, :path => '/admin',
    controllers: {
      sessions: "exo/admin/sessions"
    }
  )

  namespace :admin, module: 'admin' do
    root 'site#show', route_path: '/'

    # put '/pages/blocks', to: 'ckeditor_blocks#update'
    #devise_for :contributors, class_name: "Exo::Contributor", module: :devise, :path => '/'

    resources :contributors
    resources :settings
    resources :assets
    resources :routes, only: [:index, :show, :edit, :picture] do
      resources :settings
    end
    resources :resources, only: [:index, :show] do
      resources :items, except: :index
    end
    resources :ckeditor_assets, only: :create
  end

  get '/*route_path' => 'pages#serve_page'
end

app/models/exo/asset.rb
class Exo
  class Asset
    include Exo::Document

    field :site_slug_id
    field :name

    mount_uploader :content, Exo::AssetUploader

    field :content_type
    field :content_size

    validates_presence_of :content
    validates_integrity_of :content
    validates_presence_of :site_slug_id

    before_save :default_name

    def site
      Exo::Site.find_by slug_id: site_slug_id
    end
    
    def site= site
      self.site_slug_id = site.slug_id
    end
    
    protected
    def default_name
      name = content.url.to_s.split('.').last if content && !name
    end
  end
end

app/controllers/exo/admin/assets_controller.rb
module Exo::Admin
  class AssetsController < Exo::AdminController
    MODEL = Exo::Asset
    expose(:assets) { exo_site.slug_scope(MODEL).asc(:created_at) }
    expose(:current_asset) do
      if [:new, :create].include? params[:action].to_sym
        MODEL.new asset_params
      else
        exo_site.slug_scope(MODEL).find params[:id]
      end
    end

    def create
      current_asset.site = exo_site
      #current_asset.content = params[:upload]
      if current_asset.save
        redirect_to admin_assets_url
      else
        render 'new'
      end
    end

    def update
      if current_asset.update_attributes(asset_params)
        redirect_to admin_assets_url
      else
        render 'edit'
      end
    end

    def destroy
      current_asset.destroy
      redirect_to admin_assets_url
    end

    protected
    def asset_params
      allow_params :asset, [:name, :content, :upload]
    end
  end
end

app/views/exo/admin/assets/_form.html.haml
- if asset.new_record?
  - url = admin_assets_url
- else
  - url = admin_asset_url(asset)
= simple_form_for(asset, as: :asset, url: url, html: {class: :full_form}) do |f|
  = f.input :name
  = f.input :content, as: :file
  = f.button :submit, class: [:right, :success, :small] do
    %i.fa.fa-check
    Save
  .clear

app/views/exo/admin/assets/edit.html.haml
.title
  %h1
    %i.fa.fa-picture-o
    Edit
    = current_asset.name
    %small Asset
= render partial: 'form', locals: {asset: current_asset}

app/views/exo/admin/assets/index.html.haml
.title
  %h1
    .right
      %small
        = link_to new_admin_asset_url do
          %i.fa.fa-plus.fa-fw
          Add
    %i.fa.fa-picture-o.fa-fw
    Assets
.full_blocks
  %ul.large-block-grid-6.small-block-grid-2.medium-block-grid-3
    - assets.each do |a|
      %li
        = link_to admin_asset_url(a) do
          = image_tag a.content.thumb.url

app/views/exo/admin/assets/new.html.haml
.title
  %h1
    %i.fa.fa-picture-o
    New Asset
= render partial: 'form', locals: {asset: current_asset}

app/views/exo/admin/assets/show.html.haml
.title
  %h4
    %i.fa.fa-chevron-circle-left.fa-fw
    = link_to 'Assets', admin_assets_url
  %h1
    .right
      %small
        = link_to admin_asset_url(current_asset), 'data-method' => 'delete', confirm: 'Are you sure?', class: 'alert' do
          %i.fa.fa-trash-o.fa-fw
          Remove
    %i.fa.fa-picture-o.fa-fw
    = current_asset.name
.full_blocks{style: 'text-align: center'}
  = image_tag current_asset.content.thumb.url