config/routes.rb
Exo::Engine.routes.draw do
  if ['development', 'test'].include?(Rails.env)
    _site_grid_fs_path = '/grid_fs/exo/:site_slug_id/'
    get "#{_site_grid_fs_path}/resources/:resource_slug_id/:item_slug_id/:field_slug_id/*file_name", to: 'gridfs#item_asset'
    get "#{_site_grid_fs_path}/:id/*file_name", to: 'gridfs#asset'
  end

  root 'pages#serve_page', route_path: '/'

  # get '/admin', to: 'admin/site#show', as: 'contributor_root'
  # 
  # get '/admin', to: 'admin/site#show', as: 'admin_contributor_root'
    
  put '/admin/pages/blocks', to: 'admin/ckeditor_blocks#update'

  devise_for(
    :contributors,
    class_name: "Exo::Contributor", module: :devise, :path => '/admin',
    controllers: {
      sessions: "exo/admin/sessions"
    }
  )

  namespace :admin, module: 'admin' do
    root 'site#show', route_path: '/'

    # put '/pages/blocks', to: 'ckeditor_blocks#update'
    #devise_for :contributors, class_name: "Exo::Contributor", module: :devise, :path => '/'

    resources :contributors
    resources :settings
    resources :assets
    resources :routes, only: [:index, :show, :edit, :picture] do
      resources :settings
    end
    resources :resources, only: [:index, :show] do
      resources :items, except: :index
    end
    resources :ckeditor_assets, only: :create
  end

  get '/*route_path' => 'pages#serve_page'
end

app/models/exo/setting.rb
class Exo
  class Setting
    include Exo::Document

    embedded_in :setting_container, polymorphic: true

    field :slug_id
    field :name
    field :value
    field :required, type: Boolean, default: false
    field :system, type: Boolean, default: false

    validates_presence_of :slug_id
    validates_presence_of :name
    validates_presence_of :value, if: :required
    validate :slug_id_uniquness, if: :setting_container

    def name
      self[:name] || self.slug_id
    end

    protected
    def slug_id_uniquness
      setting_container.settings.each do |s|
        next if s == self || s.slug_id.to_s != self.slug_id
        errors.add :slug_id, :already_taken
        break
      end
    end
  end
end

app/controllers/exo/admin/settings_controller.rb
module Exo::Admin
  class SettingsController < Exo::AdminController
    skip_before_filter :verify_authenticity_token, only: :create

    MODEL = Exo::Setting

    before_filter :current_route, if: :for_route?
    helper_method :for_route?

    expose(:settings) { exo_site.settings }
    expose(:current_setting) do
      if [:new, :create].include? params[:action].to_sym
        MODEL.new new_setting_params
      else
        parent = for_route? ? current_route : exo_site
        parent.settings.find params[:id]
      end
    end
    expose(:current_route) do
      exo_site.routes.find params[:route_id]
    end

    def create
      current_setting.setting_container = for_route? ? current_route : exo_site
      if current_setting.save
        redirect_to_parent
      else
        render 'new'
      end
    end

    def update
      if current_setting.update_attributes update_setting_params
        redirect_to_parent
      else
        render 'edit'
      end
    end

    def destroy
      if current_setting.system
        flash[:alert] = "This is a system setting and cannot be required"
      else
        current_setting.destroy
      end
      redirect_to_parent
    end

    protected
    def redirect_to_parent
      redirect_to for_route? ? admin_route_url(current_route) : admin_settings_url
    end

    def for_route?
      !params[:route_id].blank?
    end

    def new_setting_params
      allow_params :setting, [:name, :slug_id, :value]
    end
    
    def update_setting_params
      allow_params :setting, [:name, :value]
    end
  end
end

app/views/exo/admin/settings/_form.html.haml
- url = nil
- if for_route?
  - url = admin_route_settings_url(current_route)
  - unless current_setting.new_record?
    - url = admin_route_setting_url(current_route, current_setting)
- else
  - url = admin_settings_url
  - unless current_setting.new_record?
    - url = admin_setting_url(current_setting)
= simple_form_for(current_setting, as: :setting, url: url, html: {class: :full_form}) do |f|
  - if current_setting.new_record?
    = f.input :slug_id
  - else
    = f.input :slug_id, disabled: true
  = f.input :name
  = f.input :value
  = link_to admin_settings_url, class: :button do
    %i.fa.fa-times-circle-o
    Cancel
  = f.button :submit, class: [:right, :success]
  .clear

app/views/exo/admin/settings/edit.html.haml
.title
  %h4
    %i.fa.fa-chevron-circle-left.fa-fw
    - if for_route?
      = link_to "Route #{current_route.path}", admin_route_url(current_route)
    - else
      = link_to 'Settings', admin_settings_url
  %h1
    .right
      %small
        - if current_setting.system
          %i.fa.fa-lock.fa-fw
        - else
          - url = admin_setting_url(current_setting)
          - url = admin_route_setting_url(current_route, current_setting) if for_route?
          = link_to url, 'data-method' => 'delete', confirm: 'Are you sure?', class: :alert do
            %i.fa.fa-trash-o.fa-fw
            Remove
    %i.fa.fa-gear.fa-fw
    Edit
    = current_setting.name
= render partial: 'form', locals: {item: current_setting}

app/views/exo/admin/settings/index.html.haml
.title
  .row
    .columns
      %h1
        %i.fa.fa-cogs.fa-fw
        Settings
%table.responsive.full
  %thead
    %tr
      %td Name
      %td Value
      %td
        = link_to new_admin_setting_url do
          %i.fa.fa-plus.fa-fw
          Add
  %tbody
    - settings.each do |s|
      %tr
        %td
          = link_to edit_admin_setting_url(s) do
            %i.fa.fa-pencil.fa-fw
            = s.name
        %td
          - if s.value
            = s.value
          - else
            %i.fa.fa-circle.fa-fw
        %td
          - if s.system
            %i.fa.fa-lock.fa-fw
          - else
            %i.fa.fa-unlock.secondary.fa-fw
          = s.slug_id

app/views/exo/admin/settings/new.html.haml
.title
  %h4
    %i.fa.fa-chevron-circle-left.fa-fw
    - if for_route?
      = link_to "Route #{current_route.path}", admin_route_url(current_route)
    - else
      = link_to 'Settings', admin_settings_url
  %h1
    %i.fa.fa-gear.fa-fw
    New setting
= render partial: 'form', locals: {item: current_setting}