config/routes.rb
Exo::Engine.routes.draw do
  if ['development', 'test'].include?(Rails.env)
    _site_grid_fs_path = '/grid_fs/exo/:site_slug_id/'
    get "#{_site_grid_fs_path}/resources/:resource_slug_id/:item_slug_id/:field_slug_id/*file_name", to: 'gridfs#item_asset'
    get "#{_site_grid_fs_path}/:id/*file_name", to: 'gridfs#asset'
  end

  root 'pages#serve_page', route_path: '/'

  # get '/admin', to: 'admin/site#show', as: 'contributor_root'
  # 
  # get '/admin', to: 'admin/site#show', as: 'admin_contributor_root'
    
  put '/admin/pages/blocks', to: 'admin/ckeditor_blocks#update'

  devise_for(
    :contributors,
    class_name: "Exo::Contributor", module: :devise, :path => '/admin',
    controllers: {
      sessions: "exo/admin/sessions"
    }
  )

  namespace :admin, module: 'admin' do
    root 'site#show', route_path: '/'

    # put '/pages/blocks', to: 'ckeditor_blocks#update'
    #devise_for :contributors, class_name: "Exo::Contributor", module: :devise, :path => '/'

    resources :contributors
    resources :settings
    resources :assets
    resources :routes, only: [:index, :show, :edit, :picture] do
      resources :settings
    end
    resources :resources, only: [:index, :show] do
      resources :items, except: :index
    end
    resources :ckeditor_assets, only: :create
  end

  get '/*route_path' => 'pages#serve_page'
end

app/models/exo/contributor.rb
class Exo
  class Contributor
    include ::Exo::Document

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, #:registerable,
           :recoverable, :rememberable, :trackable, :validatable

    field :email,              :type => String, :default => ""
    field :encrypted_password, :type => String, :default => ""

    ## Recoverable
    field :reset_password_token,   :type => String
    field :reset_password_sent_at, :type => Time

    ## Rememberable
    field :remember_created_at, :type => Time

    ## Trackable
    field :sign_in_count,      :type => Integer, :default => 0
    field :current_sign_in_at, :type => Time
    field :last_sign_in_at,    :type => Time
    field :current_sign_in_ip, :type => String
    field :last_sign_in_ip,    :type => String
    
    ##Other stuff
    
    field :name
    #field :is_able_to, type: Roles, default: Roles.new
    
    def name
      self[:name] || email.split('@').first
    end
    
    def avatar_url
      ::Gravatar.new(email).image_url
    end
    
    has_and_belongs_to_many :sites, class_name: 'Exo::Site', inverse_of: :contributors
  end
end

app/controllers/exo/admin/contributors_controller.rb
module Exo::Admin
  class ContributorsController < Exo::AdminController
    expose(:contributor) { exo_site.contributors.find params[:id] }
  end
end

app/views/exo/admin/contributors/index.html.haml
.title
  %h1
    %i.fa.fa-group.fa-fw
    Contributors
%table.responsive.full
  %thead
    %tr
      %td Name
      %td Email
  %tbody
    - exo_site.contributors.asc(:email).each do |c|
      %tr
        %td
          = link_to admin_contributor_url(c) do
            %i.fa.fa-user.fa-fw
            = c.name
            
        %td
          %a{href: "mailto:#{c.email}"}
            %i.fa.fa-envelope.fa-fw
            = c.email

app/views/exo/admin/contributors/show.html.haml
.title
  %h4
    %i.fa.fa-chevron-circle-left.fa-fw
    = link_to 'Contributors', admin_contributors_url
  %h1
    %i.fa.fa-group.fa-fw
    = contributor.name
%table.responsive.full
  %thead
    %tr
      %td Info
      %td Value
  %tbody
    %tr
      %td
        Email
      %td
        %a{href: "mailto:#{contributor.email}"}
          %i.fa.fa-envelope.fa-fw
          = contributor.email
    %tr
      %td Created at
      %td= contributor.created_at
    %tr
      %td Updated at
      %td= contributor.updated_at