config/routes.rb
Exo::Engine.routes.draw do
  if ['development', 'test'].include?(Rails.env)
    _site_grid_fs_path = '/grid_fs/exo/:site_slug_id/'
    get "#{_site_grid_fs_path}/resources/:resource_slug_id/:item_slug_id/:field_slug_id/*file_name", to: 'gridfs#item_asset'
    get "#{_site_grid_fs_path}/:id/*file_name", to: 'gridfs#asset'
  end

  root 'pages#serve_page', route_path: '/'

  # get '/admin', to: 'admin/site#show', as: 'contributor_root'
  # 
  # get '/admin', to: 'admin/site#show', as: 'admin_contributor_root'
    
  put '/admin/pages/blocks', to: 'admin/ckeditor_blocks#update'

  devise_for(
    :contributors,
    class_name: "Exo::Contributor", module: :devise, :path => '/admin',
    controllers: {
      sessions: "exo/admin/sessions"
    }
  )

  namespace :admin, module: 'admin' do
    root 'site#show', route_path: '/'

    # put '/pages/blocks', to: 'ckeditor_blocks#update'
    #devise_for :contributors, class_name: "Exo::Contributor", module: :devise, :path => '/'

    resources :contributors
    resources :settings
    resources :assets
    resources :routes, only: [:index, :show, :edit, :picture] do
      resources :settings
    end
    resources :resources, only: [:index, :show] do
      resources :items, except: :index
    end
    resources :ckeditor_assets, only: :create
  end

  get '/*route_path' => 'pages#serve_page'
end

app/views/exo/admin/resources/index.html.haml
%h1
  %i.fa.fa-folder-open
  Resources
%hr
%table.full.responsiv
  %tbody
    - exo_site.resources.asc(:name).each do |resource|
      %tr
        %td
          = link_to admin_resource_url(resource) do
            %i.fa.fa-circle
            = resource.name
        %td= resource.items.count

app/views/exo/admin/resources/show.html.haml
.title
  %h1
    %i.fa.fa-archive.fa-fw
    = current_resource.name.capitalize
%table.responsive.full
  %thead
    %tr
      %td
        Name
      %td
        Published
      %td
        = link_to new_admin_resource_item_url(current_resource) do
          %i.fa.fa-plus.fa-fw
          Add item
  %tbody
    - current_resource.items.asc(:created_at).each do |item|
      %tr
        %td
          = link_to admin_resource_item_url(current_resource, item) do
            = item.name
            - if item.name.blank?
              = "-"
        %td
          - if !item.published_at
            %i.fa.fa-circle-o.fa-fw
          - else
            - if item.published?
              %i.fa.fa-check-circle-o.fa-fw
            - else
              %i.fa.fa-clock-o.fa-fw
            = item.published_at
        %td
          = link_to admin_resource_item_url(current_resource, item), 'data-method' => 'delete', confirm: 'Are you sure?', class: 'alert' do
            %i.fa.fa-trash-o.fa-fw
            Delete